CREATE TABLE TB_USERINFO (
	USERCODE INT PRIMARY KEY,
	USERID VARCHAR(20) NOT NULL UNIQUE,
	USERPW VARCHAR(20) NOT NULL,
	USERNAME VARCHAR(30) NOT NULL,
	USERPHONE VARCHAR(11) DEFAULT '0',
	USEREMAIL VARCHAR(30)
);

CREATE TABLE TB_BOARD(
	BRDCODE INT PRIMARY KEY,
	BRDUSERCODE INT NOT NULL,
	BRDTITLE VARCHAR2(50) DEFAULT '제목없음',
	BRDWRITER VARCHAR(30) NOT NULL,
	BRDCONTENT VARCHAR2(300),
	BRDDATE DATE DEFAULT SYSDATE,
	BRDVISITED INT DEFAULT 0,
	BRDLIKE INT DEFAULT 0,
	BRDDISLIKE INT DEFAULT 0,
	CONSTRAINT BRDUSER_FK FOREIGN KEY(BRDUSERCODE) REFERENCES TB_USERINFO(USERCODE) ON DELETE CASCADE
);

CREATE TABLE TB_COMMENT(
	CMTCODE INT PRIMARY KEY,
	CMTBRDCODE INT NOT NULL,
	CMTUSERCODE INT NOT NULL,
	CMTWRITER VARCHAR2(30) NOT NULL,
	CMTCONTENT VARCHAR2(150) NOT NULL,
	CONSTRAINT CMTUSER_FK FOREIGN KEY(CMTUSERCODE) REFERENCES TB_USERINFO(USERCODE) ON DELETE CASCADE,
	CONSTRAINT CMTBRD_FK FOREIGN KEY (CMTBRDCODE) REFERENCES TB_BOARD(BRDCODE) ON DELETE CASCADE
);

CREATE TABLE TB_COIN(
	MARKETNAME VARCHAR(20) NOT NULL,
	COINPRICEKOR INT NOT NULL,
	COINPRICEENG INT NOT NULL,
	COINRATE INT,
	COINRATEPCT FLOAT,
	COINPREMIUM FLOAT,
	COINDEAL INT
);


CREATE SEQUENCE USERSEQ
	START WITH 1
	INCREMENT BY 1
;

CREATE SEQUENCE BRDSEQ
	START WITH 1
	INCREMENT BY 1
;

CREATE SEQUENCE CMTSEQ
	START WITH 1
	INCREMENT BY 1
;


select * from all_tables;

drop table TB_COIN;